apiVersion: v1
kind: Service
metadata:
  name: {{ include "lyndon-llm.fullname" . }}-backend
  labels:
    {{- include "lyndon-llm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: {{ include "lyndon-llm.fullname" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  type: ClusterIP
