apiVersion: v1
kind: Service
metadata:
  name: {{ include "lyndon-llm.fullname" . }}-qdrant
  labels:
    {{- include "lyndon-llm.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  selector:
    app.kubernetes.io/name: {{ include "lyndon-llm.fullname" . }}-qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.qdrant.service.httpPort }}
      targetPort: 6333
    - name: grpc
      port: {{ .Values.qdrant.service.grpcPort }}
      targetPort: 6334
  type: ClusterIP
