backend:
    secrets:
        llmApiKey: ""
        embeddingApiKey: ""
        langfusePublicKey: ENC[AES256_GCM,data:NyFiA+S5omX6lP4SNs6+jeL6IHvU3ibqRPU0XHtUoKSat9XPJ5D8KgAn,iv:dG/FDLsOhpp7TgiUt4Q+xbpIv486VZwsUl5ID1D3qtM=,tag:0fQQNjyKdQKlzeOCaXuiDw==,type:str]
        langfuseSecretKey: ENC[AES256_GCM,data:6gQEhNe05VsScgQINif36tlFUxMUidtIy3Hv9gBW89Yw93nh1OO/PYoe,iv:cWAjeWQvjThIrPjRv3hJ320YypMuH7ZeIwmQzMWj6Uo=,tag:yymg2FuIuH1KmqjiBvejWw==,type:str]
        jwtSecretKey: ENC[AES256_GCM,data:fNWsywsJhcCSiNPloRhUFQvTIk/9u2VJ4A18va8NOFNtpO7UcxOiBPCZ6s8Bvb1RL7/GxxJYSxATo0h8yoTeOw==,iv:+9k440gjpcDLX040jOb4Ee0Ip5LJHphxxCUzDWjnDJ8=,tag:w4n5N8v/4BtgsSthKCEphw==,type:str]
        qdrantApiKey: ""
        githubClientId: ENC[AES256_GCM,data:iGFRx28ppjFvdVLhpVzHguaODwY=,iv:IjdAZ9aLBrSg32E3bUKGFZLOG9b3hDPr214Ff60pi/8=,tag:jRmfuQfegYonTdM8+vSuSA==,type:str]
        githubClientSecret: ENC[AES256_GCM,data:Opv2eHIiGJe1r97xLlmIwkAv9y7KxvurpR2ZBLvZk6iJ4JqbEB1MRw==,iv:qBuFRSPMkWUO3EB93xUB0LlleKsAhsn0Y4LXuMnu2pU=,tag:xoqpfRqTNPJxLFWBVUtQpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1emNJc0VRRVRteFkxUkJw
            emRNQnVlOWhmbmpmc21iMUYzWTRDVG04bmtzCmJIVk9sUkw5RHZ1SU5qR2tDT1Fj
            MTJrZnRyNGpYZFNaUTFlTFZiRW5aMncKLS0tIHNGRjFydWdNeDdUYWVoZVg5eE54
            VmNQcXo2enBnei9jc3VHemsrZ2lWck0KncsZTVs0We/9E3AiQP9bP9dTudVE6U7G
            RpLFxfHSvm9b0EfEN3xgK45l/3HQetw3gAX2aCyMH8hwGFoNg5706A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18wt7x97c35fxfsknd23ah388e8gkzd3mhztmxzg334fzhq2qaeeskk4s3d
    encrypted_regex: ^(llmApiKey|embeddingApiKey|langfusePublicKey|langfuseSecretKey|jwtSecretKey|qdrantApiKey|githubClientId|githubClientSecret)$
    lastmodified: "2026-06-08T12:10:59Z"
    mac: ENC[AES256_GCM,data:tZiEMDF/vxVqaX76JS9aETuQc8EqvUbGhFVKvuAOJjkIitaRlgGbVo3ucJVkRZGbkT2Q8c6sxnrtL9vP1tHEYC2ZNOEk5md0lbtjKBSzISmI7UnPFZBctWW+CbejKbLxirN/Lwotjs3i4vnnwK1gRZ9RpcUdRLHVsat8Kpi5M8M=,iv:9qMXS4Tc/DUz9WQknM2+Lj9vRdTIDuwXwe1QjVOKVzg=,tag:dbSRH1iYUV7NH2WqTwsWcQ==,type:str]
    version: 3.13.1
