backend:
    secrets:
        llmApiKey: ""
        embeddingApiKey: ""
        langfusePublicKey: ENC[AES256_GCM,data:FYfKZgeHi9YBKMI5HzM1tSNsBJ8OXuI84kYdHf7qPeIYykciXb2i4c9J,iv:itaTdH4IkJlSRzGmFuOhEjNf+kFzRVFEaEXks/sxAh4=,tag:VCehsnrDHSGUGw8j1xivrQ==,type:str]
        langfuseSecretKey: ENC[AES256_GCM,data:4Wf3O2zFKJDBRfizBKRFmbtvAckwR+bi52KQkOxpTGXXRYeuJsSuhBs1,iv:h0Ab+VikFsxEnTwqCmRUGFwgISgrWsEYUYRI4krlwzU=,tag:ocgE2zLc0RRCLIUX5bwC/A==,type:str]
        jwtSecretKey: ENC[AES256_GCM,data:NovsqSAUryfH0isGwcO1kS1WYtkqRefmBg0fjk0Y1p/NIsVBUoNFFlxQgpFfv1Xyo1EtsgarHRu0HF8BVukzoQ==,iv:hK6MdL6eViDHbspbCehBKCKevSRHCJCVL3i68bbU4qk=,tag:Zm1XR1uTmIpAnSB8t7W/Sg==,type:str]
        qdrantApiKey: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNFV0MGsvb3Fxbmc3SmN5
            a085SGVHRUNnL3ZzalcxaXVtN1dTaUFSUlI4ClZDVUtxSVAzUzNJakxYVHl5c1BE
            SzhrTmRCZWMrSHVsUUk0dnNnODBXcHcKLS0tIGN2N1BseG9SNjVjN3REeWp6WWpi
            WlE0TzJYWkt3S3dpYmU2bnkySzBtTzQKZoHradY9wElaUkEMF+miRcS4oDDLbxim
            3sSOWzSelVJmRZ2U3m015relmdXR4gTVM0L4DKBeeGbjUYRvHCze9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18wt7x97c35fxfsknd23ah388e8gkzd3mhztmxzg334fzhq2qaeeskk4s3d
    encrypted_regex: ^(llmApiKey|embeddingApiKey|langfusePublicKey|langfuseSecretKey|jwtSecretKey|qdrantApiKey)$
    lastmodified: "2026-06-06T08:37:11Z"
    mac: ENC[AES256_GCM,data:HNjtBueJAsGvDbbBcR0nZqkUOWs8lgF/VbEjeeFWl5iQ7huTM3pqUS+wQFcY0aTVKgaAXiou1jyUec2a4pn5UC27p4I34xhQ8hO9MIUMPIVbg1Y1HV2PRwQ1xAZX2mEC1iju5lWH0qnNFIrn++FJBG+ekH9QWAUuapP6isGQjOI=,iv:u1wEigE6t3O1Xcp7cNRwB7l3mS2A+4oLKQkk0DNBSLA=,tag:tSHY4wl7pCK/zaYrgmTP1w==,type:str]
    version: 3.13.1
